name: Football AI

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  football-ai:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: تثبيت Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: تثبيت المكتبات
        run: |
          pip install -r requirements.txt

      - name: تشغيل النظام
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python main.py
