name: Football AI

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  football-ai:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4
        with:
  persist-credentials: true

      - name: تثبيت Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: تثبيت المكتبات
        run: |
          pip install -r requirements.txt

      - name: تشغيل النظام
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python main.py
      - name: حفظ المنشور في GitHub
        run: |
          git config --global user.name "Football AI Bot"
          git config --global user.email "football-ai-bot@users.noreply.github.com"
          git add latest_post.txt
          git commit -m "Add latest football post" || exit 0
          git push
